spring.application.name="server"
server.port=9090

gemini.api-key=${GEMINI_API_KEY}
# "환경변수에서 GEMINI_API_KEY 이름의 값을 가져와라"
gemini.model=gemini-3.5-flash-lite

# DB 파일 위치 - 서버를 꺼도 데이터가 남도록 파일로 저장
spring.datasource.url=jdbc:h2:file:./data/balanced-diet

# 엔티티를 보고 테이블을 자동으로 만들거나 고쳐줌
spring.jpa.hibernate.ddl-auto=update

# JPA가 실행하는 DB 명령어를 콘솔에 보여줌 (공부용)
spring.jpa.show-sql=true

# 브라우저에서 DB 내용을 볼 수 있는 화면 켜기
spring.h2.console.enabled=true

# DB 접속 사용자 이름
spring.datasource.username=sa

# DB 접속 비밀번호
spring.datasource.password=